module.exports = {
  version: '0.2',
  language: 'en,es',
  import: ['@cspell/dict-es-es/cspell-ext.json'],
  dictionaries: ['es-es'],
  allowCompoundWords: true,
  useGitignore: true,
  ignorePaths: [
    'node_modules/**',
    '.next/**',
    'coverage/**',
    'playwright-report/**',
    'test-results/**',
    'package-lock.json',
    '.husky/_/**',
    '*.min.*',
    '*.svg',
  ],
  words: [
    'FinTec',
    'supabase',
    'binance',
    'playwright',
    'hitl',
    'precommit',
    'autoscroll',
    'stricter',
    'roadmap',
    'webhook',
    'upstash',
    'dexie',
    'eslintrc',
    'tsconfig',
    'jsonc',
    'onboarding',
    'PGRST',
    'ilike',
    'plpgsql',
    'SETOF',
    'ossp',
    'partialize',
    'unconfigured',
    'KHTML',
    'zelle',
    'usdt',
    'busd',
    'openai',
    'gemini',
    'claude',
    'econnrefused',
    'enotfound',
    'bolivars',
    'sssz',
    'postgres',
    'testid',
    'redireccion',
    'clickeable',
    'clickeado',
    'clickeando',
    'clickeados',
    'revisitando',
    'clickearlo',
    'navigations',
    'montos',
    'finteclogodark',
    'categor',
    'oneof',
    'ilimitad',
    'xvcj',
    'cardano',
    'fintec',
    'bolívars',
    'paginación',
    'redirección',
  ],
};
