import {
  Account,
  AccountType,
  PaginatedResult,
  PaginationParams,
} from '@/types';
import type { RequestContext } from '@/lib/cache/request-context';
import {
  AccountsRepository,
  CreateAccountDTO,
  UpdateAccountDTO,
} from '@/repositories/contracts';
import { supabase } from './client';
import { SupabaseAccount } from './types';
import {
  mapSupabaseAccountToDomain,
  mapDomainAccountToSupabase,
  mapSupabaseAccountArrayToDomain,
} from './mappers';
import { invalidateMemoizedOwnedAccountScope } from './memoized-account-scope';
import { SupabaseClient } from '@supabase/supabase-js';
import { ACCOUNT_LIST_PROJECTION } from './account-projections';

export class SupabaseAccountsRepository implements AccountsRepository {
  private client: SupabaseClient;
  private readonly requestContext?: RequestContext;

  constructor(client?: SupabaseClient, requestContext?: RequestContext) {
    this.client = client || supabase;
    this.requestContext = requestContext;
  }

  private invalidateOwnedAccountScope(userId: string): void {
    if (!this.requestContext || this.requestContext.userId !== userId) {
      return;
    }

    invalidateMemoizedOwnedAccountScope(this.requestContext, userId);
  }

  private async getUserId(): Promise<string | null> {
    if (this.requestContext) {
      return this.requestContext.userId;
    }

    const {
      data: { user },
    } = await this.client.auth.getUser();
    return user?.id || null;
  }
  async findById(id: string): Promise<Account | null> {
    const userId = await this.getUserId();
    if (!userId) return null;

    const { data, error } = await this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION)
      .eq('id', id)
      .eq('user_id', userId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null; // Not found
      throw new Error(`Failed to find account: ${error.message}`);
    }

    return mapSupabaseAccountToDomain(data as any);
  }

  async findAll(): Promise<Account[]> {
    const userId = await this.getUserId();
    if (!userId) return [];

    const { data, error } = await this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION)
      .eq('active', true)
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      throw new Error(`Failed to fetch accounts: ${error.message}`);
    }

    return mapSupabaseAccountArrayToDomain((data as any) || []);
  }

  async findByUserId(userId: string): Promise<Account[]> {
    // Handle invalid user IDs gracefully
    if (
      !userId ||
      userId === 'local-user' ||
      userId === 'undefined' ||
      userId === 'null'
    ) {
      return []; // Return empty array for invalid user IDs
    }

    const { data, error } = await this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION)
      .eq('user_id', userId)
      .eq('active', true)
      .order('created_at', { ascending: false });

    if (error) {
      throw new Error(`Failed to fetch user accounts: ${error.message}`);
    }

    return mapSupabaseAccountArrayToDomain((data as any) || []);
  }

  async findByType(type: AccountType): Promise<Account[]> {
    const userId = await this.getUserId();
    if (!userId) return [];

    const { data, error } = await this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION)
      .eq('type', type)
      .eq('user_id', userId)
      .eq('active', true)
      .order('created_at', { ascending: false });

    if (error) {
      throw new Error(`Failed to fetch accounts by type: ${error.message}`);
    }

    return mapSupabaseAccountArrayToDomain((data as any) || []);
  }

  async findByCurrency(currencyCode: string): Promise<Account[]> {
    const userId = await this.getUserId();
    if (!userId) return [];

    const { data, error } = await this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION)
      .eq('currency_code', currencyCode)
      .eq('user_id', userId)
      .eq('active', true)
      .order('created_at', { ascending: false });

    if (error) {
      throw new Error(`Failed to fetch accounts by currency: ${error.message}`);
    }

    return mapSupabaseAccountArrayToDomain((data as any) || []);
  }

  async create(accountData: CreateAccountDTO): Promise<Account> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    const supabaseData = mapDomainAccountToSupabase({
      id: '', // Will be generated by database
      ...accountData,
      userId,
      balance: accountData.balance || 0,
      active: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    const { data, error } = await (this.client.from('accounts') as any)
      .insert(supabaseData as any)
      .select(ACCOUNT_LIST_PROJECTION)
      .single();

    if (error) {
      throw new Error(`Failed to create account: ${error.message}`);
    }

    this.invalidateOwnedAccountScope(userId);

    return mapSupabaseAccountToDomain(data);
  }

  async update(id: string, updateData: UpdateAccountDTO): Promise<Account> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    const updatePayload = {
      ...(updateData.name && { name: updateData.name }),
      ...(updateData.type && { type: updateData.type }),
      ...(updateData.currencyCode && {
        currency_code: updateData.currencyCode,
      }),
      ...(updateData.balance !== undefined && { balance: updateData.balance }),
      ...(updateData.active !== undefined && { active: updateData.active }),
      ...(updateData.minimumBalance !== undefined && {
        minimum_balance: updateData.minimumBalance,
      }),
      ...(updateData.alertEnabled !== undefined && {
        alert_enabled: updateData.alertEnabled,
      }),
      updated_at: new Date().toISOString(),
    };

    const { data, error } = await (this.client.from('accounts') as any)
      .update(updatePayload as any)
      .eq('id', id)
      .eq('user_id', userId)
      .select(ACCOUNT_LIST_PROJECTION)
      .single();

    if (error) {
      throw new Error(`Failed to update account: ${error.message}`);
    }

    this.invalidateOwnedAccountScope(userId);

    return mapSupabaseAccountToDomain(data);
  }

  async delete(id: string): Promise<void> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    // Soft delete by setting active to false
    const { error } = await (this.client.from('accounts') as any)
      .update({ active: false, updated_at: new Date().toISOString() } as any)
      .eq('id', id)
      .eq('user_id', userId);

    if (error) {
      throw new Error(`Failed to delete account: ${error.message}`);
    }

    this.invalidateOwnedAccountScope(userId);
  }

  async findPaginated(
    params: PaginationParams
  ): Promise<PaginatedResult<Account>> {
    const userId = await this.getUserId();
    if (!userId) {
      return {
        data: [],
        total: 0,
        page: params.page || 1,
        limit: params.limit || 10,
        totalPages: 0,
      };
    }

    const {
      page = 1,
      limit = 10,
      sortBy = 'createdAt',
      sortOrder = 'desc',
    } = params;
    const offset = (page - 1) * limit;

    const query = this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION, { count: 'exact' })
      .eq('active', true)
      .eq('user_id', userId)
      .range(offset, offset + limit - 1);

    // Apply sorting
    const sortColumn = sortBy === 'createdAt' ? 'created_at' : sortBy;
    query.order(sortColumn, { ascending: sortOrder === 'asc' });

    const { data, error, count } = await query;

    if (error) {
      throw new Error(`Failed to fetch paginated accounts: ${error.message}`);
    }

    return {
      data: mapSupabaseAccountArrayToDomain((data as any) || []),
      total: count || 0,
      page,
      limit,
      totalPages: Math.ceil((count || 0) / limit),
    };
  }

  async getTotalBalance(userId: string): Promise<number> {
    const { data, error } = await this.client
      .from('accounts')
      .select('balance')
      .eq('user_id', userId)
      .eq('active', true);

    if (error) {
      throw new Error(`Failed to fetch account balances: ${error.message}`);
    }

    return ((data as any[]) || []).reduce(
      (total, account) => total + (account.balance || 0),
      0
    );
  }

  async findActive(): Promise<Account[]> {
    const userId = await this.getUserId();
    if (!userId) return [];

    const { data, error } = await this.client
      .from('accounts')
      .select(ACCOUNT_LIST_PROJECTION)
      .eq('active', true)
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      // Resilience: handle missing columns during migration rollout
      if (
        error.message.includes('minimum_balance') ||
        error.message.includes('alert_enabled')
      ) {
        const fallbackProjection =
          'id,user_id,name,type,currency_code,balance,active,created_at,updated_at';
        const { data: fallbackData, error: fallbackError } = await this.client
          .from('accounts')
          .select(fallbackProjection)
          .eq('active', true)
          .eq('user_id', userId)
          .order('created_at', { ascending: false });

        if (fallbackError) {
          throw new Error(
            `Failed to fetch active accounts (fallback): ${fallbackError.message}`
          );
        }
        return mapSupabaseAccountArrayToDomain((fallbackData as any) || []);
      }
      throw new Error(`Failed to fetch active accounts: ${error.message}`);
    }

    return mapSupabaseAccountArrayToDomain((data as any) || []);
  }

  async updateBalance(id: string, newBalance: number): Promise<Account> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    const { data, error } = await (this.client.from('accounts') as any)
      .update({
        balance: newBalance,
        updated_at: new Date().toISOString(),
      } as any)
      .eq('id', id)
      .eq('user_id', userId)
      .select(ACCOUNT_LIST_PROJECTION)
      .single();

    if (error) {
      throw new Error(`Failed to update account balance: ${error.message}`);
    }

    return mapSupabaseAccountToDomain(data);
  }

  async adjustBalance(id: string, adjustment: number): Promise<Account> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    const { data: account, error: accountError } = await this.client
      .from('accounts')
      .select('id')
      .eq('id', id)
      .eq('user_id', userId)
      .single();

    if (accountError || !account) {
      throw new Error('Account not found');
    }

    const { data, error } = await (this.client as any)
      .rpc('adjust_account_balance', {
        account_id_input: id,
        adjustment_amount: adjustment,
      })
      .single();

    if (error) {
      throw new Error(`Failed to adjust account balance: ${error.message}`);
    }

    return mapSupabaseAccountToDomain(data as SupabaseAccount);
  }

  async updateBalances(
    updates: { id: string; newBalance: number }[]
  ): Promise<Account[]> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    const ids = updates.map((u) => u.id);
    const { data: accounts, error: accountsError } = await this.client
      .from('accounts')
      .select('id')
      .eq('user_id', userId)
      .in('id', ids);

    if (accountsError) {
      throw new Error(`Failed to validate accounts: ${accountsError.message}`);
    }

    const allowedIds = new Set(((accounts as any[]) || []).map((a) => a.id));
    const invalid = ids.filter((id) => !allowedIds.has(id));
    if (invalid.length > 0) {
      throw new Error('Unauthorized account update');
    }

    const { data, error } = await (this.client as any).rpc(
      'update_multiple_account_balances',
      {
        updates: updates.map((u) => ({ id: u.id, new_balance: u.newBalance })),
      }
    );

    if (error) {
      throw new Error(`Failed to update balances: ${error.message}`);
    }

    return mapSupabaseAccountArrayToDomain(data);
  }

  async getTotalBalanceByType(type: AccountType): Promise<number> {
    const userId = await this.getUserId();
    if (!userId) return 0;

    const { data, error } = await this.client
      .from('accounts')
      .select('balance')
      .eq('type', type)
      .eq('user_id', userId)
      .eq('active', true);

    if (error) {
      throw new Error(`Failed to get total balance by type: ${error.message}`);
    }

    return ((data as any[]) || []).reduce(
      (total, account: any) => total + (account?.balance || 0),
      0
    );
  }

  async getTotalBalanceByCurrency(currencyCode: string): Promise<number> {
    const userId = await this.getUserId();
    if (!userId) return 0;

    const { data, error } = await this.client
      .from('accounts')
      .select('balance')
      .eq('currency_code', currencyCode)
      .eq('user_id', userId)
      .eq('active', true);

    if (error) {
      throw new Error(
        `Failed to get total balance by currency: ${error.message}`
      );
    }

    return ((data as any[]) || []).reduce(
      (total, account: any) => total + (account?.balance || 0),
      0
    );
  }

  async getBalanceSummary(): Promise<{
    totalByType: Record<AccountType, number>;
    totalByCurrency: Record<string, number>;
    total: number;
  }> {
    const userId = await this.getUserId();
    if (!userId) {
      return {
        totalByType: {
          [AccountType.CASH]: 0,
          [AccountType.BANK]: 0,
          [AccountType.CARD]: 0,
          [AccountType.SAVINGS]: 0,
          [AccountType.INVESTMENT]: 0,
          [AccountType.CRYPTO]: 0,
        },
        totalByCurrency: {},
        total: 0,
      };
    }

    const { data, error } = await this.client
      .from('accounts')
      .select('type, currency_code, balance')
      .eq('user_id', userId)
      .eq('active', true);

    if (error) {
      throw new Error(`Failed to get balance summary: ${error.message}`);
    }

    const totalByType: Record<AccountType, number> = {
      [AccountType.CASH]: 0,
      [AccountType.BANK]: 0,
      [AccountType.CARD]: 0,
      [AccountType.SAVINGS]: 0,
      [AccountType.INVESTMENT]: 0,
      [AccountType.CRYPTO]: 0,
    };

    const totalByCurrency: Record<string, number> = {};
    let total = 0;

    ((data as any[]) || []).forEach((account: any) => {
      const balance = account?.balance || 0;

      // Sum by type
      if (account?.type in totalByType) {
        totalByType[account.type as AccountType] += balance;
      }

      // Sum by currency
      if (!totalByCurrency[account?.currency_code]) {
        totalByCurrency[account?.currency_code] = 0;
      }
      totalByCurrency[account?.currency_code] += balance;

      // Total sum
      total += balance;
    });

    return {
      totalByType,
      totalByCurrency,
      total,
    };
  }

  async createMany(data: CreateAccountDTO[]): Promise<Account[]> {
    const results: Account[] = [];

    // Process each create sequentially to maintain consistency
    for (const accountData of data) {
      const result = await this.create(accountData);
      results.push(result);
    }

    return results;
  }

  async deleteMany(ids: string[]): Promise<void> {
    const userId = await this.getUserId();
    if (!userId) {
      throw new Error('Unauthorized');
    }

    // Soft delete by setting active to false
    const { error } = await (this.client.from('accounts') as any)
      .update({ active: false, updated_at: new Date().toISOString() } as any)
      .in('id', ids)
      .eq('user_id', userId);

    if (error) {
      throw new Error(`Failed to delete accounts: ${error.message}`);
    }

    this.invalidateOwnedAccountScope(userId);
  }

  async count(): Promise<number> {
    const userId = await this.getUserId();
    if (!userId) return 0;

    const { count, error } = await this.client
      .from('accounts')
      .select('id', { count: 'exact', head: true })
      .eq('user_id', userId)
      .eq('active', true);

    if (error) {
      throw new Error(`Failed to count accounts: ${error.message}`);
    }

    return count || 0;
  }

  async exists(id: string): Promise<boolean> {
    const userId = await this.getUserId();
    if (!userId) return false;

    const { data, error } = await this.client
      .from('accounts')
      .select('id')
      .eq('id', id)
      .eq('user_id', userId)
      .eq('active', true)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return false; // Not found
      throw new Error(`Failed to check account existence: ${error.message}`);
    }

    return !!data;
  }
}
